config/routes.rb
Rails.application.routes.draw do
  resources :adversaries do
    get 'roll/:skill_id' => 'adversaries#roll', as: :roll
  end

  resources :item_qualities

  resources :talents do
    resources :connections
  end

  resources :skills do
    resources :connections
  end

  get 'generators/adversary', to: 'generators#adversary'

  get 'welcome/index'
  get 'characters', to: 'character_manager#index'

  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_scope :user do
    get "login", to: "devise/sessions#new"
    get "logout", to: "devise/sessions#destroy"
    get "register", to: "devise/registrations#new"
    get "me", to: "devise/registrations#edit"
  end
  get 'tags/:tag', to: 'adversaries#index', as: :tag
  #get '/search', to: 'search#result'
  #get '/search/reindex'

  root 'adversaries#index'

  get 'about' => 'pages#about'
  get 'updates' => 'pages#updates'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Ajax callbacks
  #get 'find/character_selection' => 'encounters#character_selection'
  #get 'find/adversary_selection' => 'encounters#adversary_selection'

end

app/models/user.rb
class User < ApplicationRecord
  #include FriendlyId
  #friendly_id :username, use: :slugged

  def should_generate_new_friendly_id?
    username_changed?
  end

  ROLES = %i[admin moderator author banned]

  def roles=(roles)
    roles = [*roles].map { |r| r.to_sym }
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
  end

  def roles
    ROLES.reject do |r|
      ((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
    end
  end

  def has_role?(role)
    roles.include?(role)
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users_controller.rb
# Users Controller
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update]
  before_action :set_page
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def set_up
    @page = 'users'
    @title = 'User'
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice:  "#{@user.username} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_user
    #@user = User.friendly.find(params[:id])
    @user = User.find(params[:id])
  end

  def set_page
    #@top_page = 'character_options'
    @page = 'users'
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :username, :enabled, :role, :superadmin_role, :editor_role, :player_role)
  end
end

app/views/users/_form.html.haml
= simple_form_for @user, html: { class: 'form-horizontal' } do |f|
  - if @user.errors.any?
    .alert-box.warning.radius{"data-alert" => ""}
      %p
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .row
    .medium-6.small-12.columns
      .row
        .small-3.columns
          = f.label :username, class: 'inline right'
        .small-9.columns
          = f.input :username, label: false
      .row
        .small-3.columns
          = f.label :email, class: 'inline right'
        .small-9.columns
          = f.input :email, label: false
      /.row
      /  .small-3.columns
      /    = f.label :first_name, class: 'inline right'
      /  .small-9.columns
      /    = f.input :first_name, label: false
      / .row
      /   .small-3.columns
      /     = f.label :last_name, class: 'inline right'
      /   .small-9.columns
      /     = f.input :last_name, label: false
      /.row
      /  .small-3.columns
      /    = f.label :enabled, class: 'inline right'
      /  .small-9.columns
      /    = f.input :enabled, label: false
      - if can? :manage, User
        .row
          .small-3.columns
            = f.label :superadmin_role, class: 'inline right'
          .small-9.columns
            = f.input :superadmin_role, as: :select, label: false
        .row
          .small-3.columns
            = f.label :editor_role, class: 'inline right'
          .small-9.columns
            = f.input :editor_role, as: :select, label: false
        .row
          .small-3.columns
            = f.label :player_role, class: 'inline right'
          .small-9.columns
            = f.input :player_role, as: :select, label: false

      .row
        .small-12.columns
          .form-actions
            = f.submit nil, class: 'button'
            - if @user.new_record?
              = link_to t('.cancel', default: t("helpers.links.cancel")), users_path, class: 'button secondary'
            - else
              = link_to t('.cancel', default: t("helpers.links.cancel")), user_path, class: 'button secondary'

app/views/users/edit.html.haml
- content_for :title do
  Edit #{@user.username}

.row
  .small-12.columns
    %h1
      Edit #{@user.username}
.row
  .small-12.columns
    = render 'form'

app/views/users/index.html.haml
- content_for :title do
  = "Users"
.title-block
  %h1.title
    Users
    - if can? :create, User
      = link_to content_tag('span', '', data: { feather: 'plus-circle' } ), new_user_path
.subtitle-block
  - if can? :create, User
    Switch
    = switch_user_select

.row
  .col-sm-12
    %table.table.table-striped#users-index{style: "width: 100%;"}
      %thead.thead-dark
        %tr
          %th Username
          %th Email
          %th Role
          %th Sign ins
          %th Last sign in
          %th
      - @users.each do |user|
        %tbody
          %tr
            %td= user.username
            %td= user.email
            %td=# user.role
            %td= user.sign_in_count
            %td= user.last_sign_in_at
            %td= link_to "<i class='fi-pencil'>edit</i>".html_safe, edit_user_path(user)