config/routes.rb
Rails.application.routes.draw do
  resources :adversaries do
    get 'roll/:skill_id' => 'adversaries#roll', as: :roll
  end

  resources :item_qualities

  resources :talents do
    resources :connections
  end

  resources :skills do
    resources :connections
  end

  get 'generators/adversary', to: 'generators#adversary'

  get 'welcome/index'
  get 'characters', to: 'character_manager#index'

  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_scope :user do
    get "login", to: "devise/sessions#new"
    get "logout", to: "devise/sessions#destroy"
    get "register", to: "devise/registrations#new"
    get "me", to: "devise/registrations#edit"
  end
  get 'tags/:tag', to: 'adversaries#index', as: :tag
  #get '/search', to: 'search#result'
  #get '/search/reindex'

  root 'adversaries#index'

  get 'about' => 'pages#about'
  get 'updates' => 'pages#updates'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Ajax callbacks
  #get 'find/character_selection' => 'encounters#character_selection'
  #get 'find/adversary_selection' => 'encounters#adversary_selection'

end

app/models/skill.rb
class Skill < ApplicationRecord
  include FriendlyId
  friendly_id :name, use: :slugged

  validates :name, :characteristic, :skill_type, presence: true
  validates :name, uniqueness: true

  default_scope { order(skill_type: :asc, name: :asc, created_at: :asc) }
  scope :social_skills_ordered_by_skill_name, -> { where("skills.skill_type = ?", 'Social') }
  scope :general_skills_ordered_by_skill_name, -> { where("skill_type = ?", 'General') }
  scope :knowledge_skills_ordered_by_skill_name, -> { where("skills.skill_type = ?", 'Knowledge') }
  scope :combat_skills_ordered_by_skill_name, -> { where("skills.skill_type = ?", 'Combat') }
  scope :magic_skills_ordered_by_skill_name, -> { where("skills.skill_type = ?", 'Magic') }

  def should_generate_new_friendly_id?
    name_changed?
  end

  def is_career_skill(character, talent_select = false)
    # Build an array of career skill ids granted by character's career.
    career_skill_ids = Array.new
    if character.career
      character.career.bonus_skills.each do |bs|
        career_skill_ids << bs.skill_id
      end
    end

    # Add career skills granted by character's archetype.
    character.archetype.bonus_skills.each do |bs|
      if bs.career_skill
        career_skill_ids << bs.skill_id
      end
    end

    # And finally add career skill ids granted by talents.
    character.character_talents.each do |ct|
      ct.bonus_skills.each do |bs|
        if bs.career_skill
          career_skill_ids << bs.skill_id
        end
      end
    end

    career_skill_ids.include?(id)
  end

  def search_data
    {
      name: name,
      skill_type: skill_type,
      created_at: created_at,
      updated_at: updated_at
    }
  end

  def self.facets_search(params)
    query = params[:search][:query].presence || "*"
    conditions = {}
    conditions[:skill_type] = params[:search][:skill_type] if params[:search][:skill_type].present?

    search query, where: conditions,
      aggs: {:skill_type => {}},
      page: params[:page],
      per_page: 50,
      order: {
        skill_type: :asc,
        name: :asc
      },
      type: self
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  include ApplicationHelper
  include SkillsHelper

  before_action :set_skill, only: [:show, :edit, :update, :destroy]
  #after_action :update_setting_indices, only: [:create, :update]

  load_and_authorize_resource
  skip_authorize_resource only: [:index]

  # GET /skills
  # GET /skills.json
  def index
    params[:search] = set_search_params_cookiee(params)
    @skills = Skill.all #.facets_search(params)
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
  end

  # GET /skills/new
  def new
    @skill = Skill.new
  end

  # GET /skills/1/edit
  def edit
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = Skill.new(skill_params)

    respond_to do |format|
      if @skill.save
        format.html { redirect_to @skill, notice: 'Skill was successfully created.' }
        format.json { render :show, status: :created, location: @skill }
      else
        format.html { render :new }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skills/1
  # PATCH/PUT /skills/1.json
  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to @skill, notice: 'Skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @skill }
      else
        format.html { render :edit }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    #GenesysApi.new.delete_indices_for_item('Skill', @skill.id)
    @skill.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to skills_url, notice: 'Skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def update_setting_indices
      GenesysApi.new.set_object_indices(@skill)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skill_params
      params.require(:skill).permit(:name, :description, :characteristic, :skill_type, :slug)
    end
end

app/helpers/skills_helper.rb
module SkillsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/skills/_form.html.haml
= simple_form_for @skill, html: { role: 'form' } do |f|
  .row.row-eq-height
    .col-md-6.col-sm-12
      .card.card-block
        .form-group
          = f.label :name, class: "control-label"
          = f.input :name, input_html: { class: "form-control boxed" }, label: false
        .form-group
          = f.label :characteristic, class: "control-label"
          = f.input :characteristic, as: :select, collection: ['Agility', 'Brawn', 'Cunning', 'Intellect', 'Presence', 'Willpower'], label: false, input_html: { class: "form-control boxed" }
        .form-group
          = f.label :skill_type, class: "control-label"
          = f.input :skill_type, as: :select, collection: ['Social', 'General', 'Knowledge', 'Combat', 'Magic'], label: false, input_html: { class: "form-control boxed" }
        .form-group
          = f.submit nil, class: 'btn btn-primary'
          = link_to t('.cancel', default: t("helpers.links.cancel")), skills_path, class: 'btn btn-secondary'
  .row
    .col-sm-12
      .card.card-block
        .form-group
          = f.label :description, class: "control-label"
          = f.input :description, placeholder: 'Skill description', label: false, as: :text, input_html: { rows: 20, cols: 25, class: 'tinymce form-control' }

= tinymce

app/views/skills/edit.html.haml
.title-block
  %h3.title Edit Skill
  %p.title-description Basic description and settings for skills

.subtitle-block
  %h3.subtitle= @skill.name

%section.section
  = render 'form'

app/views/skills/index.html.haml
- content_for :title do
  Skills

.d-flex.justify-content-between.flex-wrap.flex-md-nowrap.align-items-center.pt-3.pb-2.mb-3.border-bottom
  %h1 Skills
  .btn-toolbar.mb-2.mb-md-0
    .btn-group.mr-2
      - if can? :create, @skill
        /%button.btn.btn-sm.btn-outline-secondary Share
        = link_to "New".html_safe, new_skill_path, class: "btn btn-sm btn-outline-secondary"
      %button.btn.btn-sm.btn-outline-secondary Print
.subtitle-block
  =# render "search/facets", path: skills_path, facets: @skills.aggs
.row
  .card-columns
    - @skills.each do |skill|
      .card.skill.example.mb-3{ class: "card-skilltype-#{skill.skill_type}"}
        .card-header.text-center
          = skill.skill_type
        .card-body.bg-transparent
          %h4.card-title
            = skill.name
            %br
            ="[#{skill.characteristic}]"
          = text_replace_tokens(skill.description.html_safe)

        - if can? :manage, @skill
          .p-0.action-links
            %ul.nav.justify-content-center
              %li.nav-item
                = link_to content_tag('span', '', data: { feather: 'trash' } ), skill, data: {confirm: "Are you sure you want to delete '#{skill.name}'?"}, method: :delete, class: 'nav-link remove'
              %li.nav-item
                = link_to content_tag('span', '', data: { feather: 'edit-2' } ), edit_skill_path(skill), class: 'nav-link edit'

app/views/skills/new.html.haml
.title-block
  %h3.title New Skill
  %p.title-description Basic description and settings for skills

.subtitle-block
  %h3.subtitle= @skill.name

%section.section
  = render 'form'

app/views/skills/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @skill.name
%p
  %b Description:
  = @skill.description.html_safe
%p
  %b Characteristic:
  = @skill.characteristic
%p
  %b Type:
  = @skill.skill_type


= link_to 'Edit', edit_skill_path(@skill)
\|
= link_to 'Back', skills_path