config/routes.rb
Rails.application.routes.draw do
  resources :adversaries do
    get 'roll/:skill_id' => 'adversaries#roll', as: :roll
  end

  resources :item_qualities

  resources :talents do
    resources :connections
  end

  resources :skills do
    resources :connections
  end

  get 'generators/adversary', to: 'generators#adversary'

  get 'welcome/index'
  get 'characters', to: 'character_manager#index'

  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_scope :user do
    get "login", to: "devise/sessions#new"
    get "logout", to: "devise/sessions#destroy"
    get "register", to: "devise/registrations#new"
    get "me", to: "devise/registrations#edit"
  end
  get 'tags/:tag', to: 'adversaries#index', as: :tag
  #get '/search', to: 'search#result'
  #get '/search/reindex'

  root 'adversaries#index'

  get 'about' => 'pages#about'
  get 'updates' => 'pages#updates'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Ajax callbacks
  #get 'find/character_selection' => 'encounters#character_selection'
  #get 'find/adversary_selection' => 'encounters#adversary_selection'

end

app/models/item_quality.rb
class ItemQuality < ApplicationRecord
end

app/controllers/item_qualities_controller.rb
class ItemQualitiesController < ApplicationController
  before_action :set_item_quality, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource
  skip_authorize_resource only: [:index]

  # GET /item_qualities
  # GET /item_qualities.json
  def index
    @item_qualities = ItemQuality.all
  end

  # GET /item_qualities/1
  # GET /item_qualities/1.json
  def show
  end

  # GET /item_qualities/new
  def new
    @item_quality = ItemQuality.new
  end

  # GET /item_qualities/1/edit
  def edit
  end

  # POST /item_qualities
  # POST /item_qualities.json
  def create
    @item_quality = ItemQuality.new(item_quality_params)

    respond_to do |format|
      if @item_quality.save
        format.html { redirect_to @item_quality, notice: 'Item quality was successfully created.' }
        format.json { render :show, status: :created, location: @item_quality }
      else
        format.html { render :new }
        format.json { render json: @item_quality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item_qualities/1
  # PATCH/PUT /item_qualities/1.json
  def update
    respond_to do |format|
      if @item_quality.update(item_quality_params)
        format.html { redirect_to @item_quality, notice: 'Item quality was successfully updated.' }
        format.json { render :show, status: :ok, location: @item_quality }
      else
        format.html { render :edit }
        format.json { render json: @item_quality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_qualities/1
  # DELETE /item_qualities/1.json
  def destroy
    @item_quality.destroy
    respond_to do |format|
      format.html { redirect_to item_qualities_url, notice: 'Item quality was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_quality
      @item_quality = ItemQuality.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_quality_params
      params.require(:item_quality).permit(:name, :description, :activation)
    end
end

app/helpers/item_qualities_helper.rb
module ItemQualitiesHelper
end

app/views/item_qualities/_form.html.haml
= form_for @item_quality do |f|
  - if @item_quality.errors.any?
    #error_explanation
      %h2= "#{pluralize(@item_quality.errors.count, "error")} prohibited this item_quality from being saved:"
      %ul
        - @item_quality.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :activation
    = f.text_field :activation
  .actions
    = f.submit 'Save'

app/views/item_qualities/_item_quality_rank_fields.html.haml
.nested-fields.mt-2
  .form-group.col-sm-8
    = f.input :item_quality_id, as: :select, collection: ItemQuality.all, label: false, input_html: { class: "form-control boxed" }
  .form-group.col-sm-2
    = f.label :ranks, class: "control-label"
    = f.input :ranks, label: false, input_html: { class: "form-control boxed" }
  .form-group.col-sm-2
    = link_to_remove_association "Remove quality", f
  %hr

app/views/item_qualities/_quality_expand_info.html.haml
%div{ id: "ItemQualities#{type}#{item_id}" }
  - qualities.each_with_index do |q, index|
    %a.badge.badge-primary.mr-1{"aria-controls" => "#collapse_quality-#{index}-#{q[:id]}", "aria-expanded" => "false", "data-toggle" => "collapse", :href => "#collapse_quality-#{index}-#{q[:id]}", :role => "button"}
      ="#{q[:name]}#{' ' if q[:ranked]}#{q[:ranks] if q[:ranked]}".strip
  - qualities.each_with_index do |q, index|
    .row.mt-1
      .col
        .collapse{id: "collapse_quality-#{index}-#{q[:id]}", "data-parent" => "#ItemQualities#{type}#{item_id}"}
          .card.card-body
            - if q[:description].present?
              %strong="#{q[:name]}#{' ' if q[:ranks] != 0}#{q[:ranks] if q[:ranks] != 0}".strip
              = text_replace_tokens(q[:description])

app/views/item_qualities/edit.html.haml
%h1 Editing item_quality

= render 'form'

= link_to 'Show', @item_quality
\|
= link_to 'Back', item_qualities_path

app/views/item_qualities/index.html.haml
%h1 Listing item_qualities

%table
  %thead
    %tr
      %th Name
      %th Description
      %th Activation
      %th
      %th
      %th

  %tbody
    - @item_qualities.each do |item_quality|
      %tr
        %td= item_quality.name
        %td= item_quality.description
        %td= item_quality.activation
        %td= link_to 'Show', item_quality
        %td= link_to 'Edit', edit_item_quality_path(item_quality)
        %td= link_to 'Destroy', item_quality, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Item quality', new_item_quality_path

app/views/item_qualities/new.html.haml
%h1 New item_quality

= render 'form'

= link_to 'Back', item_qualities_path

app/views/item_qualities/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @item_quality.name
%p
  %b Description:
  = @item_quality.description
%p
  %b Activation:
  = @item_quality.activation

= link_to 'Edit', edit_item_quality_path(@item_quality)
\|
= link_to 'Back', item_qualities_path