config/routes.rb
Rails.application.routes.draw do
  resources :adversaries do
    get 'roll/:skill_id' => 'adversaries#roll', as: :roll
  end

  resources :item_qualities

  resources :talents do
    resources :connections
  end

  resources :skills do
    resources :connections
  end

  get 'generators/adversary', to: 'generators#adversary'

  get 'welcome/index'
  get 'characters', to: 'character_manager#index'

  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_scope :user do
    get "login", to: "devise/sessions#new"
    get "logout", to: "devise/sessions#destroy"
    get "register", to: "devise/registrations#new"
    get "me", to: "devise/registrations#edit"
  end
  get 'tags/:tag', to: 'adversaries#index', as: :tag
  #get '/search', to: 'search#result'
  #get '/search/reindex'

  root 'adversaries#index'

  get 'about' => 'pages#about'
  get 'updates' => 'pages#updates'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Ajax callbacks
  #get 'find/character_selection' => 'encounters#character_selection'
  #get 'find/adversary_selection' => 'encounters#adversary_selection'

end

app/views/layouts/_flash.html.haml
- if flash[:error]
  .alert.alert-danger{ role: "alert" }
    = h flash[:error].html_safe
- if flash[:notice]
  .alert.alert-warning{ role: "alert" }
    = h flash[:notice].html_safe
- if flash[:success]
  .alert.alert-success{ role: "alert" }
    = h flash[:success].html_safe
- if flash[:alert]
  .alert.alert-danger{ role: "alert" }
    = h flash[:alert].html_safe

app/views/layouts/_footer.html.haml
%footer.footer
  .footer-block.buttons
    %iframe.footer-github-btn{:frameborder => "0", :height => "20px", :scrolling => "0", :src => "https://ghbtns.com/github-btn.html?user=modularcode&repo=modular-admin-html&type=star&count=true", :width => "140px"}
  .footer-block.author
    %ul
      %li
        created by
        %a{:href => "https://github.com/modularcode"} ModularCode
      %li
        %a{:href => "https://github.com/modularcode/modular-admin-html#get-in-touch"} get in touch

app/views/layouts/_header.html.haml
%header
  / Fixed navbar
  %nav.navbar.navbar-expand-md.navbar-dark.fixed-top.bg-dark
    %a.navbar-brand{:href => "/"} Genesys - Adversary Bank
    %button.navbar-toggler{"aria-controls" => "navbarCollapse", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarCollapse", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarCollapse.collapse.navbar-collapse
      %ul.navbar-nav.mr-auto
        %li.nav-item{ class: current_class?(root_path) }
          =# link_to 'Home', root_path, class: 'nav-link'
        - if user_signed_in?
          %li.nav-item{ class: current_class?(me_path) }
            = link_to 'Profile', me_path, class: 'nav-link'
          %li.nav-item
            = link_to 'Sign out', logout_path, class: 'nav-link'
            / Right Nav Section
      %ul.right.navbar-nav
        %li.nav-item
          = link_to 'RPG Dice Roller', 'http://rpg-dice-roller.herokuapp.com/genesys', target: "_blank", class: 'nav-link'
        %li.nav-item{class: ("active" if current_page('updates'))}
          #{link_to 'Updates', updates_path, class: 'nav-link'}
        %li.nav-item{class: ("active" if current_page('about'))}
          #{link_to 'About', about_path, class: 'nav-link'}
        /%li= render 'layouts/paypal_donate'
        %li.nav-item= render 'layouts/patreon'
        %li.nav-item
          .nav-link or
        %li.nav-item= render 'layouts/kofi_donate'

        =#%form.form-inline.mt-2.mt-md-0
        =#  %input.form-control.mr-sm-2{"aria-label" => "Search", :placeholder => "Search", :type => "text"}/
        =#  %button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Search

app/views/layouts/_kofi_donate.html.erb
<a href='https://ko-fi.com/C0C6C0XN' target='_blank'><img height='30' style='border:0px;height:36px;' src='https://az743702.vo.msecnd.net/cdn/kofi4.png?v=0' border='0' alt='Buy Me a Coffee at ko-fi.com' /></a>

app/views/layouts/_main_menu.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#">Launchbay</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/_notifications.html.haml
%li.notifications.new
  %a{"data-toggle" => "dropdown", :href => ""}
    %i.fa.fa-bell-o
    %sup
      %span.counter 8
  .dropdown-menu.notifications-dropdown-menu
    %ul.notifications-container
      %li
        %a.notification-item{:href => ""}
          .img-col
            .img{:style => "background-image: url('assets/faces/3.jpg')"}
          .body-col
            %p
              %span.accent Zack Alien
              pushed new commit:
              = succeed "." do
                %span.accent Fix page load performance issue
      %li
        %a.notification-item{:href => ""}
          .img-col
            .img{:style => "background-image: url('assets/faces/5.jpg')"}
          .body-col
            %p
              %span.accent Amaya Hatsumi
              started new task:
              = succeed "." do
                %span.accent Dashboard UI design.
      %li
        %a.notification-item{:href => ""}
          .img-col
            .img{:style => "background-image: url('assets/faces/8.jpg')"}
          .body-col
            %p
              %span.accent Andy Nouman
              deployed new version of
              %span.accent NodeJS REST Api V3
    %footer
      %ul
        %li
          %a{:href => ""} View All

app/views/layouts/_patreon.html.erb
<a href="https://www.patreon.com/bePatron?u=283886" data-patreon-widget-type="become-patron-button">Become a Patron!</a><script async src="https://c6.patreon.com/becomePatronButton.bundle.js"></script>

app/views/layouts/_profile_dropdown.html.haml
%li.profile.dropdown
  %a.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
    - if current_user.respond_to? :gravatar_url
      = image_tag current_user.gravatar_url, class: 'img'
    %span.name
      = current_user.username
  .dropdown-menu.profile-dropdown-menu{"aria-labelledby" => "dropdownMenu1"}
    %a.dropdown-item{:href => "/me"}
      %i.fa.fa-user.icon
      Profile
    /%a.dropdown-item{:href => "#"}
    /  %i.fa.fa-bell.icon
    /  Notifications
    /%a.dropdown-item{:href => "#"}
    /  %i.fa.fa-gear.icon
    /  Settings
    .dropdown-divider
    %a.dropdown-item{:href => "/logout"}
      %i.fa.fa-power-off.icon
      Logout

app/views/layouts/_sidebar.html.haml
%nav.col-md-2.d-none.d-md-block.bg-dark.navbar-dark.sidebar.d-print-none#NavBarLeft
  /%nav.navbar.navbar-expand-md.navbar-dark.bg-dark.sidebar
  .sidebar-sticky
    %ul.nav.flex-column
      =#%li.nav-item= link_to "#{image_tag('icons/svg/skill.svg', class: 'menu-item-icon')} Skills".html_safe, skills_path, class: "nav-link #{current_class?(skills_path)}"
      =#%li.nav-item= link_to "#{image_tag('icons/svg/talent.svg', class: 'menu-item-icon')} Talents".html_safe, talents_path, class: "nav-link #{current_class?(talents_path)}"
      =#%li.nav-item= link_to "#{image_tag('icons/svg/elf.svg', class: 'menu-item-icon')} Races".html_safe, archetypes_path, class: "nav-link #{current_class?(archetypes_path)}"
      =#%li.nav-item= link_to "#{image_tag('icons/svg/class.svg', class: 'menu-item-icon')} Careers".html_safe, careers_path, class: "nav-link #{current_class?(careers_path)}"
      =#%li.nav-item= link_to "#{image_tag('icons/svg/carrot-and-stick.svg', class: 'menu-item-icon')} Motivations".html_safe, motivations_path, class: "nav-link #{current_class?(motivations_path)}"

    - if current_user.superadmin_role
      %h6.sidebar-heading.d-flex.justify-content-between.align-items-center.px-3.mt-4.mb-1.text-muted
        %span Gensys Admin
      %ul.nav.flex-column.mb-2
        =#%li.nav-item= link_to "#{image_tag('icons/svg/friendship.svg', class: 'menu-item-icon')} Manage Users".html_safe, users_path, class: "nav-link"
        =#%li.nav-item= link_to "#{image_tag('icons/svg/adventurer.svg', class: 'menu-item-icon')} Manage Characters".html_safe, characters_path, class: "nav-link"
    =# 'Icons made by <a href="https://www.freepik.com/" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/"          title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a>'.html_safe

app/views/layouts/application.html.haml
!!!
%html.no-js{:lang => "en"}
  %head
    / Required meta tags
    %meta{:charset => "utf-8"}/
    %meta{:content => "ie=edge", "http-equiv" => "x-ua-compatible"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    / Place favicon.ico in the root directory
    %title
      = content_for?(:title) ? yield(:title) : (@title ? @title : "")
      | Adversaries of Genesys
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag "application", media: 'print'

    %script{:crossorigin => "anonymous", :integrity => "sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN", :src => "https://code.jquery.com/jquery-3.2.1.slim.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4", :src => "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"}

    = javascript_include_tag 'tinymce'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    %link{:href => "https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css", :rel => "stylesheet"}/
    = stylesheet_link_tag "select2-bootstrap4.min", media: 'all'
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"}

  %body{:class => "#{controller_name} #{action_name}"}
    -# if user_signed_in?
    -# if current_page?(root_path) || current_page?(adversaries_path) || current_page?(adversary_path)
    - if user_signed_in? || ['adversaries', 'skills', 'talents', 'pages', 'generators'].include?(params[:controller])
      = render partial: 'layouts/header'
      .container-fluid
        .row
          =# render partial: 'layouts/sidebar'
          %main.col-md-12.ml-sm-auto.col-lg-12.px-4{:role => "main"}
            /= render partial: 'layouts/flash'
            = yield
    - else
      = yield
    / Optional JavaScript
    / jQuery first, then Popper.js, then Bootstrap JS
    %script{:charset => "utf8", :src => "https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js", :type => "text/javascript"}
    = javascript_include_tag 'bootstrap'
    = javascript_include_tag 'jquery.knob'
    :javascript
      feather.replace()

app/views/layouts/modal.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}
    = stylesheet_link_tag "application"
    = csrf_meta_tags
  %body
    .modal-header
      %h5#exampleModalLabel.modal-title= @modal_title
      %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
        %span{"aria-hidden" => "true"} ×
    = yield

    /.row
    /  .small-11.columns
    /    = yield
    /  .small-1.columns
    /    %button.close-button{"aria-label" => "Close reveal", "data-close" => "", :type => "button"}
    /      %span{"aria-hidden" => "true"} &times;